### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by kurdo2000** [2000GHz/OfflineParty#54]
I'm having this error when running 5. Read usernames from user_list.txt

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 6301027 (char 6301026)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\extra\OfflineParty-v1.4.5\download.py", line 884, in <module>
    read_user_txt_list()
  File "D:\extra\OfflineParty-v1.4.5\download.py", line 461, in read_user_txt_list
    urls, labels, json_data = user_search(username)
                              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\extra\OfflineParty-v1.4.5\user_search.py", line 118, in main
    combined_data = fetch_creator_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\extra\OfflineParty-v1.4.5\user_search.py", line 10, in fetch_creator_data
    coomer_data = requests.get("https://coomer.su/api/v1/creators.txt").json()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting ',' delimiter: line 1 column 6301027 (char 6301026)

This is my user_list.txt
https://coomer.su/onlyfans/user/x
https://coomer.su/onlyfans/user/x
https://coomer.su/onlyfans/user/x
https://coomer.su/onlyfans/user/x

**Comment by kurdo2000** [comment]
It's mentioned to log in to coomer, I have an account but how to link it with this program? And would that solve the problem?

**Comment by 2000GHz** [comment]
> It's mentioned to log in to coomer, I have an account but how to link it with this program? And would that solve the problem?

Hello, sorry for the delayed response, to link coomer with the program all you have to do is have your account logged in on your default browser, the program will automatically sync.

Also, trying your user_list didn't give me any errors, I understand hiding the usernames for privacy reasons, but it could be an error with the parsing of the username that I can't take a look at without seeing it "uncensored"

In any case, this was most likely a server issue since these lines:

`coomer_data = requests.get("[https://coomer.su/api/v1/creators.txt").json(](https://coomer.su/api/v1/creators.txt%22).json())
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting ',' delimiter: line 1 column 6301027 (char 6301026)`

Make it clear that the error is with the server JSON, not your user list

Hope it was solved and again, sorry for the delay, happy new year :)
